client
dev tun
proto tcp
remote 127.0.0.1 7070
resolv-retry infinite
nobind
persist-key
persist-tun
ca /root/ca.crt				
cert /root/vpn_client_1.crt	
key /root/vpn_client_1.key		
cipher AES-256-CBC
verb 3
