pc1[0]=A

r1[0]=A
r1[1]=B
r1[2]=C
r1[3]=D

r2[0]=B
r2[1]=E

r3[0]=D
r3[1]=G

r4[0]=E
r4[1]=C
r4[2]=G
r4[3]=H

#-----------------------------------------------

r5[0]=H
r5[1]=I
r5[2]=J
r5[3]=K

r6[0]=K
r6[1]=L
r6[2]=M
r6[3]=N

s1[0]=N

r7[0]=O
r7[1]=J
r7[2]=M
r7[3]=P

r8[0]=I
r8[1]=L
r8[2]=O
r8[3]=R

#-----------------------------------------------

r9[0]=R
r9[1]=S

pc2[0]=S

s2[0]=S

#-----------------------------------------------

r10[0]=P
r10[1]=Q

pc3[0]=Q
s3[0]=Q
