port 1194
dev tun
proto udp
ca /root/ca.crt
cert /root/myserver.crt
key /root/myserver.key
# Diffie hellman parameters. Generate your own with:
# openssl dhparam -out dh2048.pem 2048
#Per usare la cifratura ellittica
# dh none 
dh /usr/share/doc/openvpn/examples/sample-keys/dh2048.pem

topology subnet
server 10.8.0.0 255.255.255.0
keepalive 10 120
cipher AES-256-CBC
persist-key
persist-tun
status openvpn-status.log
log openvpn.log
verb 3
explicit-exit-notify 1

client-to-client